### PR TITLE
Choose same day when relative time is later than current

### PR DESCRIPTION
**Pull request by justanotherdot**
Hi! Sorry for not opening an issue first. I had a specific use case to tailor
this to so I hacked at getting this to work, but still within the confines of the
tests I've provided to demonstrate what I was running up against.

In cases such as "Monday 4pm", Chronic currently does not give the same
day when the time is later than what is given in `currently`. For
example, "Monday 4pm", when `currently` is a Monday and at 7am, will yield
_next_ Monday, but "Tuesday 4pm" will yield the following day. I've provided 
a failing test to demonstrate as the first commit.

This was a bit of a surprise and I've adjusted the code to first check
that if we are on the same day of week and the time is later to return
back the requested time for the current day rather than the next
matching day of week.

### CODE REVIEW

**Comment by radar** [comment]
Thank you very much @justanotherdot :) 

I have hand-merged this as I had some WIP work with adding Credo that was interfering with it. I'm waiting on the Travis tests and when they're green I'll take a look at doing a 3.1 release of Chronic with your changes.

**Comment by radar** [comment]
Done. Chronic 3.1 is out there in the wild :)

**Comment by radar** [comment]
I've now also explained this in the README: https://github.com/radar/chronic#chronic-uses-universal-time-by-default

**Comment by justanotherdot** [comment]
Thanks for the prompt response! I was (am?) still a little confused as to what the ideal behaviour here is. If you ask Siri on an iPhone to schedule something for "Tuesday 8pm" and it's before that time but on a Tuesday, she'll set it to next Tuesday, but that doesn't quite fit into the use case we were using so I hope this isn't a breaking change that some people are relying on already. 

If it is, it might be nice to have some kind of way to tweak this to get what you want, maybe an extra option that let's you set which you prefer (`:maintain_same_day` or whatever). I could doll that up if you ever need it since I'm now a bit more familiar with the code.

**Pull request closed without merging**
